name: Build and Push Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./Frontend/my-genai-stack
          file: ./Frontend/my-genai-stack/Dockerfile
          push: true
          tags: |
            suryaprakash08/lowcode-frontend:latest
            suryaprakash08/lowcode-frontend:v${{ github.run_number }}
